### ISSUE TITLE
Fail to install kytos/of_lldp because of missing Ethertype Class

### ISSUE THREAD

**Issue by viniarck** [kytos/of_lldp#4]
Guys, 

I was trying to use the official kytos napps, namely, `of_lldp` with the latest commit on this repo `64e0609 (HEAD -> master, origin/master) Merge pull request #2 from cemsbr/fix-port-type`, and there's an ImportError going on because of there's a missing EtherType on the package `pyof.foundation.network_types`. 

To reproduce:

1. Git clone/setup
```
git clone https://github.com/kytos/kytos.git

#!/bin/sh

pip install -e .[dev]
python setup.py develop || break
```
2. Install `of_core` and `of_lldp`

```
❯ pip freeze G python-openflow
python-openflow==2017.2b1

~/repos/kytos master*
❯ pip freeze G kytos
-e git+https://github.com/kytos/kytos.git@2ab51ea4e86b15bdb419adb2b3fcd4f80c362fe8#egg=kytos
kytos-utils==2017.2b1

~/repos/kytos master*
❯ kytos napps list
No NApps found.

~/repos/kytos master*
❯ kytos napps install kytos/of_core
INFO  NApp kytos/of_core:
INFO    Searching local NApp...
INFO    Not found. Downloading from NApps Server...
INFO    Downloaded and installed.
INFO    Enabling...
INFO    Enabled.

~/repos/kytos master* 7s
❯ kytos napps install kytos/of_lldp
INFO  NApp kytos/of_lldp:
INFO    Searching local NApp...
INFO    Not found. Downloading from NApps Server...
INFO    Downloaded and installed.
INFO    Enabling...
INFO    Enabled.
INFO  NApp kytos/of_core:
INFO    Enabled.
INFO  Installing Dependencies:
INFO  NApp kytos/of_core:
INFO    Installed.
INFO    Enabled.

~/repos/kytos master*
❯ glog
commit 2ab51ea4e86b15bdb419adb2b3fcd4f80c362fe8
Merge: c108b9a 30ddb0f
Author: Beraldo Leal <beraldo.leal@cern.ch>
Date:   Wed Sep 27 17:39:42 2017 -0300

    Merge pull request #588 from cemsbr/fix-install

    Fix install by blacklisting a setuptools version


~/repos/kytos master*
❯ kytos napps list

Status |       NApp ID       |                           Description
=======+=====================+=================================================================
 [ie]  | kytos/of_core:0.1.1 | OpenFlow Core of Kytos Controller, responsible for main OpenF...
 [ie]  | kytos/of_lldp:0.1.1 | Discover switches in the network using the LLDP protocol.

Status: (i)nstalled, (e)nabled

```

3. Notice the following ImportError:

```
❯ kytosd -f
2017-09-28 10:41:10,018 - INFO [kytos.core.logs] (MainThread) Logging config file "/home/arcanjo/repos/kytos/.direnv/python-3.6.1/etc/kytos/logging.ini" loaded successfully.
2017-09-28 10:41:10,019 - INFO [kytos.core.controller] (MainThread) /home/arcanjo/repos/kytos/.direnv/python-3.6.1/var/run/kytos
2017-09-28 10:41:10,019 - INFO [kytos.core.controller] (MainThread) Starting Kytos - Kytos Controller
2017-09-28 10:41:10,020 - INFO [kytos.core.tcp_server] (TCP server) Kytos listening at 0.0.0.0:6633
2017-09-28 10:41:10,020 - WARNING [werkzeug] (API server) WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance.
2017-09-28 10:41:10,020 - INFO [kytos.core.controller] (RawEvent Handler) Raw Event Handler started
2017-09-28 10:41:10,022 - INFO [kytos.core.controller] (MsgInEvent Handler) Message In Event Handler started
2017-09-28 10:41:10,022 - INFO [kytos.core.controller] (MsgOutEvent Handler) Message Out EventHandler started
2017-09-28 10:41:10,022 - INFO [kytos.core.controller] (AppEvent Handler) App Event Handler started
2017-09-28 10:41:10,022 - INFO [kytos.core.controller] (MainThread) Loading Kytos NApps...
2017-09-28 10:41:10,023 - INFO [kytos.core.napps.napp_dir_listener] (MainThread) NAppDirListener Started...

  _          _
 | |        | |
 | | ___   _| |_ ___  ___
 | |/ / | | | __/ _ \/ __|
 |   <| |_| | || (_) \__ \
 |_|\_\\__, |\__\___/|___/
        __/ |
       |___/

Welcome to Kytos SDN Platform!

We are doing a huge effort to make sure that this console will work fine. But
for now is still experimental.

Kytos website.: https://kytos.io/
Documentation.: https://docs.kytos.io/
OF Address....: tcp://0.0.0.0:6633
WEB UI........: http://0.0.0.0:8181/
kytos $> 2017-09-28 10:41:32,468 - INFO [root] (kytos/of_core) Running NApp: <Main(kytos/of_core, started 140344056813312)>
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/arcanjo/repos/kytos/.direnv/python-3.6.1/lib/python3.6/site-packages/watchdog/observers/api.py", line 199, in run
    self.dispatch_events(self.event_queue, self.timeout)
  File "/home/arcanjo/repos/kytos/.direnv/python-3.6.1/lib/python3.6/site-packages/watchdog/observers/api.py", line 368, in dispatch_events
    handler.dispatch(event)
  File "/home/arcanjo/repos/kytos/.direnv/python-3.6.1/lib/python3.6/site-packages/watchdog/events.py", line 537, in dispatch
    _method_map[event_type](event)
  File "/home/arcanjo/repos/kytos/kytos/core/napps/napp_dir_listener.py", line 69, in on_created
    self._controller.load_napp(*napp)
  File "/home/arcanjo/repos/kytos/kytos/core/controller.py", line 590, in load_napp
    napp_spec.loader.exec_module(napp_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/home/arcanjo/repos/kytos/.direnv/python-3.6.1/var/lib/kytos/napps/kytos/of_lldp/main.py", line 7, in <module>
    from pyof.foundation.network_types import LLDP, Ethernet, EtherType
ImportError: cannot import name 'EtherType'
```

If you browse pyof.doundation.network_types there's no EtherType class in this module.

**Comment by diraol** [comment]
@viniciusarcanjo take a look at the latest python-openflow source code (master branch), EtherType was added a week ago: https://github.com/kytos/python-openflow/commit/8f000bf15ac960c844266ab6dc417fa20cce80f9

**Comment by viniarck** [comment]
@diraol 

kytos master repo is installing this version of `python-openflow`, which I doubled check on pipy, and this version was uploaded on 2017-09-19. I'll find a way to install everything from master. It would be great if you guys could provide an easy way to pull everything from master and install on develop mode, I'd appreciate if you could have any script that you bootstrap your environment. 

```
❯ grep -r python-openflow
tox.ini:    git+git://github.com/kytos/python-openflow.git
.direnv/python-3.6.1/lib/python3.6/site-packages/python_openflow-2017.2b1.dist-info/metadata.json:{"classifiers": ["License :: OSI Approved :: MIT License", "Operating System :: POSIX :: Linux", "Programming Language :: Python :: 3.6", "Topic :: System :: Networking", "Topic :: Software Development :: Libraries"], "extensions": {"python.details": {"contacts": [{"email": "devel@lists.kytos.io", "name": "Kytos Team", "role": "author"}], "document_names": {"description": "DESCRIPTION.rst"}, "project_urls": {"Home": "http://github.com/kytos/python-openflow"}}}, "extras": ["dev"], "generator": "bdist_wheel (0.29.0)", "license": "MIT", "metadata_version": "2.0", "name": "python-openflow", "run_requires": [{"extra": "dev", "requires": ["Sphinx (~=1.5.0)", "coverage", "pip-tools", "sphinx-autobuild", "sphinx-bootstrap-theme (~=0.4.0)", "sphinx-rtd-theme", "tox", "yala"]}], "summary": "Library to parse and generate OpenFlow messages", "version": "2017.2b1"}
.direnv/python-3.6.1/lib/python3.6/site-packages/python_openflow-2017.2b1.dist-info/METADATA:Name: python-openflow
.direnv/python-3.6.1/lib/python3.6/site-packages/python_openflow-2017.2b1.dist-info/METADATA:Home-page: http://github.com/kytos/python-openflow
```

```
~/repos/kytos master*
❯ pip freeze G python-openflow
python-openflow==2017.2b1
```

Thanks for this prompt reply!

**Comment by viniarck** [comment]
I updated to master, and it was fixed, I'm closing this issue. I'd appreciate you could share a script that always pull the dependencies from master though. Thanks!

```
❯ pip freeze G openflow
-e git+https://github.com/kytos/kytos.git@2ab51ea4e86b15bdb419adb2b3fcd4f80c362fe8#egg=python_openflow
```
